### ISSUE TITLE
Fix security updates as listed by Dependabot 

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/data.js#115]
## Tasks
- [ ] Fix the security updates as listed by Dependabot

## Acceptance criteria 
- [ ] We don't see security alert when we visit the repo.
- [ ] The listed security updates are fixed.
