### ISSUE TITLE
Option to download only part of the large files

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data.js#12]
When working with large remote files, we have to download the entire file to generate a schema. However, it is not the desired behaviour and we want to improve it. E.g., we want to download only some part of the file (10k rows) and use it to generate the schema.

## Acceptance criteria

* [ ] I can use `rows` method with `limit` option and set number of rows I need.

## Tasks

* [ ] refactor `File.rows` method
* [ ] refactor `FileRemote.stream` method
* [ ] refactor CSV parser

## Analysis

By concluding "old" analysis below, we can see that the main thing we have to refactor is `FileRemote.stream` method. As `rows` method triggers stream method we have to setup passing number of rows from there. We also need to refactor CSV parser to also take argument with number of rows, because we want to remove left over rows came from `stream` method - we cannot get exact N rows as we are reading chunk by chunk and destroying connection once it reaches N.

// OLD

### Infer schema with first 10k of rows

According to README from tableschema, that is possible. We need to implement this in the `data.js` repo in `addSchema` method of File class:

https://github.com/frictionlessdata/tableschema-js/tree/906a70c749248d2b32904c141dd8142d345682be#async-tableinferlimit100

```javascript=
table.infer({limit: 10000})
```

However, we could implement this somewhere "deeper" so it can be useful in the future (e.g., in `rows` method). We could set limit argument in the `rows` method so we can set number of rows required. It can be useful for other methods as well, e.g., for info or cat commands:

```javascript=
rows({keyed, limit} = {}) {
  return this._rows({keyed, limit})
}

_rows({keyed, limit} = {}) {
  if (this.descriptor.format in parserDatabase) {
    const parser = parserDatabase[this.descriptor.format]
    return parser(this, keyed, limit)
  }
  ...
}

// in the parser
const csvParser = async (file, keyed = false, limit) => {
  const stream = await file.stream()
  const parseOptions = getParseOptions(file.descriptor.dialect, keyed, limit)
  return stream.pipe(parse(parseOptions))
}

const getParseOptions = (dialect, keyed, limit) => {
  ...
  if (limit) {
    parseOptions.to = limit
  }

  return parseOptions
}
```

### Get only part of file with node-fetch

The goal is to download only first 10k rows of the given tabular file (if non-tabular we don't download at all). To do so we can read every received chunk and count new line characters. Once it reaches 10k we destroy the response:

:::info
I had difficulties and spend a lot of time trying to implement it using `node-fetch`. It looks like destroy method for response is not exposed - [issue link](https://github.com/bitinn/node-fetch/pull/204). It was decided to expose that method but it was stuck there and never included into the master branch.
:::

```javascript=
const https = require('https')

https.get('https://raw.githubusercontent.com/datasets/un-locode/master/data/code-list.csv', (res) => {
  let rowCount = 0
  res.on('data', (chunk) => {
    rowCount += chunk.toString().split('\n').length - 1
    if (rowCount > 9999) {
      res.destroy()
    }
  })
})
```

**Comment by rufuspollock** [comment]
@anuveyatsu aren't stream and rows already streams so we can just shut off the stream when we've read as much as we need -- i.e. why do we need special new options (can't consumers take care of using these streams sensibly themselves ...)?

**Comment by anuveyatsu** [comment]
@rufuspollock it seems I was confused when doing the analysis. Our main goal is to don't download entire file when adding schema, which can be simply done with tableschema by setting limit property. In fact, by default, it is reading only first 100 rows:

```javascript
async infer({limit=100}={}) {
...
}
```

So this:

```javascript
const rows = await toArray(await this.rows())
this.descriptor.schema = await infer(rows)
```

should just pass location of the file to the infer method:

```javascript
this.descriptor.schema = await infer(this.path)
```

**Comment by rufuspollock** [comment]
@anuveyatsu can you pass a row stream to infer or not? I'd prefer not to pass the path (e.g. does infer support urls and local paths etc)

**Comment by anuveyatsu** [comment]
@rufuspollock yes, infer supports URLs and paths. Need to test for row stream

**Comment by anuveyatsu** [comment]
@rufuspollock no, tableschema-js does not support a row stream as a source - https://github.com/frictionlessdata/tableschema-js/blob/master/src/table.js#L220-L253

I've opened an issue about this - https://github.com/frictionlessdata/tableschema-js/issues/92

**Comment by anuveyatsu** [comment]
INVALID - we will implement passing stream as source to tableschema's `infer` method so this issue becomes invalid - https://github.com/frictionlessdata/tableschema-js/issues/95
