### ISSUE TITLE
parsePath does not work with urls that don't have conventional filename

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data.js#18]
At the moment, our `parsePath` function is quite basic (https://github.com/datahq/data.js/blob/master/lib/index.js#L194-L206). It always expects that there'll be regular file name in the URLs, e.g., https://example.com/path/myfile.csv, however, we have number of cases when it does not work. For example, URLs from world bank api - http://api.worldbank.org/indicator/NY.GDP.MKTP.CD?format=csv - wouldn't work as our function would guess that filename is "NY.GDP.MKTP" and format is "CD":

```javascript
const parsePath = (path_, basePath = null) => {
  const isItUrl = isUrl(path_) || isUrl(basePath)
  // eslint-disable-next-line no-useless-escape
  const fileName = path_.replace(/^.*[\\\/]/, '')
  const extension = path.extname(fileName)
  return {
    path: path_,
    pathType: isItUrl ? 'remote' : 'local',
    name: fileName.replace(extension, ''),
    format: extension.slice(1),
    mediatype: mime.lookup(path_) || ''
  }
}
```

Problem: when loading File objects from URL our `parsePath` function returns wrong descriptor if the URL doesn't have conventional filename. E.g., this works OK:

https://example.com/path/myfile.csv

however, this does not work:

https://example.com/path/myfile?format=csv

## Acceptance criteria

* [x] I can instantiate File object from URL and set the format by providing `format` argument: `File.load(URL, {format: 'csv'})`

## Tasks

* [x] refactor parsePath function
* [x] refactor File.load method

## Analysis

:::info
Once following is implemented we will need to add `--format` option in the CLI so publishers can do `data push URL --format=csv`:

* in `cat` command
* in `push` command
* in `get` command - when getting single file
* in `info` command
* `init` (?)
:::

Taking into consideration comments from Rufus, we decided to:

* have `parsePath` function refactored so it behaves differently than for local paths and URLs
* implement having `format` option when instantiating File objects

For all URLs we are expecting `format` to be provided. If it is not provided when instantiating File objects, `format: ''` is empty string for URLs. This allows us to eliminate wrong format generation.

> No, i would still try to guess for urls if not provided ...
> If you really got fancy what you'd do is check that hte mimetype makes sense and if not warn in some way.

### `parsePath` function refactoring

Format is important as it allows us to decide whether the file is tabular or not. So we know if we should generate a schema for it.

```javascript=
const parsePath = (path_, basePath = null, format = '') => {
  const isItUrl = isUrl(path_) || isUrl(basePath)
  if (isUrl) {
    .... 
} else {
  const fileName = path_.replace(/^.*[\\\/]/, '')
}
  // eslint-disable-next-line no-useless-escape
  const extension = path.extname(fileName)
  const descriptor = {
    path: path_,
    pathType: isItUrl ? 'remote' : 'local',
    name: fileName.replace(extension, ''),
    format: extension.slice(1),
    mediatype: mime.lookup(path_) || ''
  }

  if (isItUrl) {
    descriptor.format = format
  }
  
  return descriptor
}
```

and it should be passed from `File.load` method:

```javascript=
static load(pathOrDescriptor, {basePath, format} = {}) {
  ...
  if (lodash.isPlainObject(pathOrDescriptor)) {
    ...
  } else if (lodash.isString(pathOrDescriptor)) {
    descriptor = parsePath(pathOrDescriptor, basePath, format)
  } ...
}
```

**Comment by rufuspollock** [comment]
I think:

* We should parse urls different from local paths
* There is nothing much we could do about the world bank file path and its extension (there are various complex heuristic we *could* use to have worked out this was not an extension but nothing obvious!)
* We need to probably be able to pass an explicit format to this function (in which case we don't try try and split out the extension ...)

I think this affects:

```
data cat
data push
data init (?)
```

I think we want to add some kind of --format=... option.

**Comment by anuveyatsu** [comment]
FIXED. Next step is to handle passing `format` from CLI tool: https://github.com/datahq/datahub-cli/issues/197
