### ISSUE TITLE
Setup travis and fix tests with fixtures

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data.js#2]
We want to have all tests are fixed and travis setup
## Acceptance criteria

* [x] All tests fixed
* [x] Travis setup

## Tasks

* [x] Fix all tests
* [x] Add `.travis.yml`

**Comment by anuveyatsu** [comment]
FIXED
