### ISSUE TITLE
Add this repo into script for creating milestones and into the board

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data.js#3]
## Acceptance criteria

* [x] Added into list of repos in our script for creating/closing milestones
* [x] Added into board

## Tasks

* [x] add to list of repos
* [x] add to board

**Comment by Mikanebu** [comment]
https://raw.githubusercontent.com/datopian/ourbot/master/extras/closeMilestones.js

**Comment by Mikanebu** [comment]
FIXED
