### ISSUE TITLE
Include dataset and file class description into README 

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data.js#5]
We want to have our README.md with class descriptions and usage. 

## Acceptance criteria 

* [ ] Nicely written `README.md` with `Dataset` and `File` class description and usage 

## Tasks

* [x] Introduction
* [x] Quick start
* [x] Add section for `File` class
* [x] Add sections for `Dataset` class

**Comment by Mikanebu** [comment]
FIXED

**Comment by rufuspollock** [comment]
@Mikanebu this was definitely not FIXED 😄  - there were no proper docs for File or Dataset. I've just added these now.
