### ISSUE TITLE
Make Browser related code separated from the main lib

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/data.js#69]
Make the lib so that the all browser related code will not affect to Node environment and vise versa. 

## Acceptance criteria

* [x] Existing tests pass after the change
* [x] Can use the lib in Node without errors
  * [x] It doesn't throw `[browser related variable] is not defined` error

## Tasks

* [x] Separate Browser related implementation which requires Browser specific classes
* [x] Make those functions callable from main lib regardless the platform (browser/node)

Related #50
