### ISSUE TITLE
Reimplement parseDatasetIdentifier function

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data.js#7]
Analysis of this issue is in https://github.com/datahq/datahub-cli/issues/144

## Acceptance criteria

* [x] satisfies these 4 scenarios - https://github.com/datahq/datahub-cli/issues/144#issuecomment-321982954

## Tasks

* [x] refactor `parseDatasetIdentifier` function in `/lib/index.js`
* [x] copy and refactor tests from cli repo

**Comment by anuveyatsu** [comment]
FIXED
