### ISSUE TITLE
Latest tests are failing

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data.js#81]
See https://github.com/datopian/data.js/actions/runs/253706377

## Acceptance criteria

* [x] Tests are passing 😄 

## Tasks

* [x] Debug the tests
* [x] Fix the bug
