### ISSUE TITLE
Rename and move datajs to frictionlessdata

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data.js#85]
I think this library should become the main JS library  ~~base level frictionless "driver" / sdk for JS~~ in the Frictionless project. This would imply:

* Relocating to github.com/frictionlessdata/frictionless-js
* ~~Renaming to `frictionless-driver-js` or similar (naming for this is still tbc)~~
* Pushing to NPM as `frictionless`

~~Note we would want to build a higher level `frictionless-js` lib like the `frictionless-py` lib on top of it.~~ This would be the high level lib for now.

## Acceptance

* [x] Located in frictionlessdata project __Done__ https://github.com/frictionlessdata/frictionless-js
* [x] Renamed on Github __Done__ https://github.com/frictionlessdata/frictionless-js
* [x] Renamed on npm (keep old data.js there so we don't break anything old and start releasing as frictionless on npm) __Done__ https://www.npmjs.com/package/frictionless.js

## Tasks

* [x] Delete https://github.com/frictionlessdata/frictionless-js (stub repo) __Done__
* [x] Move this repo to frictionlessdata org __Done__ https://github.com/frictionlessdata/frictionless-js
* [x] Rename to `frictionless-js` __Done__
* [x] Update the `package.json` and README __Done__
* [x] Republish to npm as `frictionless.js` (unfortunately `frictionless` is taken) __Done__ https://www.npmjs.com/package/frictionless.js
  * [x] Make datopian "user" an owner
* [x] Update any dependencies we know of e.g. ckan-client-js, Datapub to use this __Done__ https://github.com/datopian/ckan-client-js/pull/35 https://github.com/datopian/datapub/pull/70

**Comment by lwinfree** [comment]
sounds great!

**Comment by risenW** [comment]
__Note:__ We need to update the Travis and Github CI links

**Comment by risenW** [comment]
@mariorodeghiero @kmanaseryan We have moved the data.js repo to frictionless. Please update the name in any dependency using datajs directly from github

**Comment by risenW** [comment]
@rufuspollock This is all done and ready to close

**Comment by rufuspollock** [comment]
@risenW great, you can close this. Before doing that however i would recommend updating all acceptance criteria done with **bolded** evidence of it being done e.g. link to npm package etc. Similarly in tasks maybe worth mentioning what downstream packages you have updated.

All done now.

**Comment by rufuspollock** [comment]
@risenW you also want to close the issue as per https://playbook.datopian.com/issues-tasks/#closing-issues e.g. FIXED etc with a comment. Do you want to try doing that.

**Comment by risenW** [comment]
> @risenW you also want to close the issue as per https://playbook.datopian.com/issues-tasks/#closing-issues e.g. FIXED etc with a comment. Do you want to try doing that.

Yes, I will update it now

**Comment by risenW** [comment]
FIXED. See https://www.npmjs.com/package/frictionless.js and https://github.com/frictionlessdata/frictionless-js
