### ISSUE TITLE
Release the library properly and document installation

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data.js#88]
## Acceptance criteria

* [ ] I have a major release re recent changes
* [ ] I can install it via package registry using both `NPM` and `Yarn`
* [ ] I have docs about how to install it in NodeJS environment
* [ ] I have docs about how to install it using `NPM` and `Yarn` but for browser environment, eg, when developing a React app
* [ ] I have docs about how to install it in browsers

**Comment by risenW** [comment]
@rufuspollock, In addition to the acceptance criteria above by @anuveyatsu, I'm proposing doing the following before release:
* refactoring the classes in the main script [index](https://github.com/datopian/data.js/blob/master/src/index.js) to separate modules. This will make it more manageable and easier for contributors to work with. 
* Using ES6 import and export instead of require

what are your thoughts on this?

**Comment by rufuspollock** [comment]
@risenW I think that refactoring makes sense. I've added those items to the task list in the description. Please go ahead and work on them.

/cc @kmanaseryan

**Comment by risenW** [comment]
Alright, noted!

**Comment by risenW** [comment]
## Tasks

Tasks
* [x] Refactor data.js main script into submodules
* [x] Refactor code base to ES6 specification
* [x] Refactor test suite from ava to mocha (It is easier to set up testing suites using for mocha)
* [ ] Update docstrings for classes and methods
* [x] Update installation guides for users and developers
