### ISSUE TITLE
Make File.descriptor a property

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data.js#9]
## Acceptance criteria

* [x] File.descriptor is accessed as a property using get accessor

## Tasks

* [x] Make it "private": descriptor => _descriptor
* [x] Convert to get accessor

**Comment by anuveyatsu** [comment]
FIXED
