### ISSUE TITLE
Refactor the code to generate the hashes only using stream API

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/data.js#93]
So recently in #90 has been implemented a function which reads the large data by chunks in the browser which lets to generate hashes for the large files.

The problem is we don't take advantage from stream API, since every `FIle` like class has `stream()` function. 

## Acceptance criteria
- [x] The hashes are being generated using streams() in browser
- [x] The hashes are being generated using streams() in Node
- [x] Can generate a hash from large files using only streams (>1GB) in Browser
- [x] Can generate a hash from large files using only streams (>1GB) in Node

## Tasks

- [x] Try hash large files in Node. 
  - [x] If it fails then do the same as we do for the browser (reading by chunks, and updating the hash for every new chunk till we get the last chunk)
- [x] In `FileInterface.generateHash()` instead of using `readChunked()` method, use `stream()` method. Try to achive the same result using streams. It should be something like this: 
```js
      const stream = await this.stream({ size: -1 })

      stream.on('error', (err) => reject(err))
      stream.on('data', (chunk) => {
        newHash.update(chunk)
      })
      stream.on('end', () => {
        resolve(newHash.digest('hex'))
      })
```
This might not work, becuase of the current implementation of `stream()`, see next step. So make the nesseary changes so that you can use streams and achive the same result as using `readChunked()`. 
- [ ] Current `FileInterface.stream()` function uses `toNodeStream()` function which seems doesn't behaves like a real stream. It reads by chunk, but it pushes all the chunks as a one stream at the end. Needs more investigation here. (This step can be handled in the last)
- [x] Once you succeed remove `readChunked()` from the code

**Comment by risenW** [comment]
@kmanaseryan There is a tradeoff for reading streams in the browser. Currently, if we use the [stream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/getReader) implementation:

```javascript
async _computeHashInBrowser(algorithm, done) {

  let hash = crypto.createHash(algorithm)
  let fileSize = this.size

  const reader = this.descriptor.stream().getReader()

  async function read(reader, totalChunkSize = 0, chunkCount = 0) {
    const {value, done} = await reader.read()
  
    if (done) {
      let finalHash = hash.digest('hex')
      return finalHash
    }
 
    hash.update(value)
  
    return read(reader, runningTotal, chunkCount + 1);
  }
  
  const finalHash = await read(reader);
  console.log(`Hashing Complete. Final Hash:${finalHash}`);
  
}
```

 we can not set the chunk size, and this defaults to 64kb in chrome-quite small. If we use the readChunk by @mariorodeghiero  approach, then we can set a chunk size but we'll be using the FileReader Interface. 

I guess we can argue that the Filereader interface doesn't work as a traditional stream, but we have to have to consider these chunk size tradeoff.

**Comment by rufuspollock** [comment]
i don't think we need config chunk size if default is quite small e.g. 64kb.

**Comment by risenW** [comment]
> i don't think we need config chunk size if default is quite small e.g. 64kb.

@rufuspollock Yea, there is no need for that, 64kb works quite okay. I've made the update, see #95
