### ISSUE TITLE
Improve README for API usage

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/data.js#97]
## Acceptance criteria
- [x] API section is separated from README __Done__ https://github.com/frictionlessdata/frictionless-js/tree/update-doc/docs
- [x] jsdoc-to-markdown is installed in dev deps __Done__ 
- [x] Can run `yarn docs`, which will generate .mds (would be great if we can automatically save into _./doc/API.md_ file __Done__ 

## Tasks
- [x] Separate API section into another markdown. See how it is done in https://github.com/datopian/ckan-client-js/tree/master/docs __Done__ https://github.com/frictionlessdata/frictionless-js/pull/112
- [x] Use https://www.npmjs.com/package/jsdoc-to-markdown to gen JS Doc comments to .md __Done__ https://github.com/frictionlessdata/frictionless-js/pull/112
