### ISSUE TITLE
Make stream() a generic for all File like classes

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/data.js#98]
## Acceptance criteria

- [x] We use one `hash()` function for every File classes
- [x] `hash256()` is back and deprecated 
- [x] We have one `stream()` function for the given class i.e. each class has it's own implementation of `stream()` method. So unlike `hash()` which can be inherited by parent class, this stream might be different depending on which environment (node vs browser) we are or whether the file is inline or not. 
- [x] The user of `stream()` function has no idea about the implementation 

## Tasks

- [x] Move back `hash256()`
- [x] ~Remove `chunkedBuffer()` since we already have `stream()`~
